services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: job-board-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: job-board
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - job-board-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-board-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/job-board?authSource=admin
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongodb
    networks:
      - job-board-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  # MongoDB Express (Optional - for database management)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: job-board-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - job-board-network

volumes:
  mongodb_data:

networks:
  job-board-network:
    driver: bridge
